require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - '**/bin/**/*'
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/CaseIndentation:
  IndentOneStep: true
Layout/ClassStructure:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/EmptyLineAfterMultilineCondition:
  Enabled: true
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Disabled for specs to allow following pattern:
# expect { Foo.create }.to change { Foo.count }
Lint/AmbiguousBlockAssociation:
  Exclude:
    - '**/spec/**/*'
Lint/NumberConversion:
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 5
Metrics/MethodLength:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 5

Naming/VariableNumber:
  EnforcedStyle: snake_case

# We're preferring this from a stylistic point of view; it does not actually
# impact performance
Performance/ArraySemiInfiniteRangeSlice:
  Enabled: true
Performance/CaseWhenSplat:
  Enabled: true
Performance/IoReadlines:
  Enabled: true

RSpec/ContextWording:
  Prefixes:
    - as
    - by
    - when
    - with
    - without
RSpec/DescribedClassModuleWrapping:
  Enabled: true
RSpec/EmptyLineAfterExample:
  Enabled: false
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/NamedSubject:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/ArrayCoercion:
  Enabled: true
Style/AutoResourceCleanup:
  Enabled: true
Style/ClassMethodsDefinitions:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/DateTime:
  Enabled: true
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/ExponentialNotation:
  EnforcedStyle: scientific
Style/IpAddresses:
  Enabled: true
Style/Lambda:
  EnforcedStyle: literal
Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - '**/spec/**/*'
Style/MultilineMethodSignature:
  Enabled: true
Style/OptionHash:
  Enabled: true
Style/RedundantBegin:
  Enabled: true
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/Send:
  Enabled: true
Style/StringMethods:
  Enabled: true
Style/TrailingCommaInBlockArgs:
  Enabled: true
Style/ZeroLengthPredicate:
  Enabled: true

# Specific for Gilded Rose
Style/BisectedAttrAccessor:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
